[features]
seeds = false
skip-lint = false
[programs.localnet]
bgl_path_validator = "PATHrLe2WkDq1WS9df5dSuZ5MhnZZzGZmXcj4wGFCys"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/kelliott/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
